### ISSUE TITLE
All shortcuts removed and app no longer allow me add new keys or even import

### ISSUE THREAD

**Issue by anime2010** [mikecrittenden/shortkeys#115]
Hello,

noticed today that the app no longer work and no longer allow add shortcuts and can not import codes etc its totally bugged i removed and reinstalled and its same 

using chrome btw

**Comment by tortino** [comment]
similar experience for me too: using old version I added single key shortcuts to go to previous tab (b) and to next tab (n). it was working as expected.
now shortcuts doesn't work anymore, and new version is completely different and difficult to use.
I have tried to add again my shortcuts but I can't: it is impossibile to select a behaviour because "select behaviour" menu is empty.

**Comment by mikecrittenden** [comment]
Sorry about this - looks like the 2.2.6 Chrome package was corrupted. I just uploaded 2.2.7 which should fix this once your Chrome updates you. I'll keep it open until someone can confirm.

**Comment by mikecrittenden** [comment]
Ok 2.2.7 is confirmed to fix it. To speed up the update, you can go to chrome://extensions, click "Developer mode" then "Update extensions now"

**Comment by tortino** [comment]
new version works
thanks


2017-12-17 12:54 GMT+01:00 Mike Crittenden <notifications@github.com>:
