### ISSUE TITLE
shortcut for previous next tab dont work while page is loading

### ISSUE THREAD

**Issue by yennor** [mikecrittenden/shortkeys#130]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: firefox 57
* Operating System and version: debian linux stretch

When I enter a new url, press enter, then the page starts loading, when I press then the shortcut for previoux/next tab (F1 or F2), the shortcut mostly doesn't work, I need to wait until the page loading advanced a littlebit more (until it got the first reply from the server or something). It is really annoying since there are a lot of pages which needs a while to be loaded and I don't really like to watch them loading.
I guess I already know the answer, that it is not a bug, but has something to do with the new plugin system of firefox. In that case, would you mind opening a bug there (I really have no idea where and how to describe it properly for them)

**Comment by mikecrittenden** [comment]
Yeah, unfortunately there's nothing we can do about that in Firefox. In the Chrome version, Chrome allows us to set keyboard shortcuts at the browser level rather than the page level, which fixes it, but Firefox doesn't have support for that just yet. Because of that, we just have to inject the keyboard shortcut listener into the page you're viewing, which can only happen once the page is finished loading. Sorry about that. :(

**Comment by mikecrittenden** [comment]
Here's the bug ticket for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1320332
