### ISSUE TITLE
Add action: "Activate an extension"

### ISSUE THREAD

**Issue by CRImier** [mikecrittenden/shortkeys#141]
Would this be doable? I want to override F1 with an "Activate an extension" action - Chrome doesn't allow me to rebind F1, but Shortkeys doesn't allow me to "Activate an extension". Is this a possible feature for Shortkeys to have? If not, is there any workaround you know of?

**Comment by mikecrittenden** [comment]
Can you explain what you mean by "activate an extension"? Do you mean turn the extension on (like the same thing as going to the Chrome extensions page and enabling it)? Or something else?

**Comment by CRImier** [comment]
It's the equivalent of "pressing on the extension icon on the top bar", for example, if you press on the Shortkeys icon, it opens the default 5-element context menu (Shortkeys..., Parameters, Delete, etc.), Ublock opens its own custom window with buttons etc. This is how Chrome calls it, when you go to the Chrome's "Keybindings" page, most extensions will have that available as an action. I'm not an extension developer (yet), so I don't know the correct term to call it, sorry.

**Comment by mikecrittenden** [comment]
Unfortunately the extension API doesn't currently allow one extension to trigger the browser action (i.e., the button) of another one so I don't believe there's anything we can do here. I'm guessing you're trying to set up a shortcut for an extension that doesn't already have an option for that in Chrome's keybindings? If so, all I can think is to try contacting the developers of that extension and point them at https://developer.chrome.com/apps/commands, since setting that up on their end should take all of like 2 minutes (it's just a single addition to manifest.json).

**Comment by CRImier** [comment]
As I said already, the "Activate" action is exposed - I just need to bind F1 to it, but can't do so from Chrome "Keybindings" page. Thank you for the explanation, and for the great extension! =)

**Comment by mikecrittenden** [comment]
Oh I see, so it IS available on the keybindings page but F1 isn't an allowed shortcut for it. Sorry I misunderstood. Yeah, Chrome keybindings are really annoying in that way - they all require command/ctrl or alt.
