### ISSUE TITLE
Trigger another shortcut doesn't work

### ISSUE THREAD

**Issue by apieum** [mikecrittenden/shortkeys#144]
I want to change F6 shortcut (move to next frame) with "trigger another shortcut" and it doesn't work.
I've tried all steps described in FAQ, then the same shortcut to do other actions works, and finally to trigger ctrl + k or ctrl + pageup shortcuts doesn't work too.

## Your Environment
* Shortkeys version: 2.2.27
* Browser name and version: Firefox 57.0.4 64bit
* Operating System and version: Fedora 27  Linux-4.14.11-300.fc27.x86_64 x86_64 GNU/Linux

**Comment by aimeefortel** [comment]
**Attending answer** from **apieum**.
Waiting for his answer 👍 
I want to change **CTRL + SHIFT + Q** . Actually This combinaison **CLOSE** the windows FIREFOX !
I want to change to : **DO NOTHING**
Why ? Because another application in background is waiting for Ctrl+Shift+Q

How is the procedure ? If I add a key, when I type these three keyboard keys, Firefox is CLOSING instantly...

Thanks

**Comment by mikecrittenden** [comment]
@aimeefortel The best you can do there is this: 

![2018-02-12 at 9 29 am](https://user-images.githubusercontent.com/32261/36101400-38983baa-0fd7-11e8-8140-03f9fcae551f.png)

If that doesn't work then it's because Firefox doesn't allow that shortcut to be disabled which means there isn't anything that Shortkeys can do.

**Comment by uqiu** [comment]
![8888888888851](https://user-images.githubusercontent.com/25265788/41198212-9ad6e038-6ca6-11e8-802e-89c040939d96.jpg)
this doesnt work.

**Comment by apieum** [comment]
Sorry I missed your replies. Your extension is no working at all I've moved forward. 
Even basic functionalities are doing nothing.

![Screenshot 2018-06-10 17-14-58](https://user-images.githubusercontent.com/723728/41203010-e75c5688-6cd1-11e8-9bb3-e798934b53e9.png)
