### ISSUE TITLE
Firefox not disabled ctrl+n, ctrl+t

### ISSUE THREAD

**Issue by diegoles** [mikecrittenden/shortkeys#231]
Firefox not disabled ctrl+n, ctrl+t

**Comment by abatkin** [comment]
Firefox also does not disable ctrl+q

**Comment by zw963** [comment]
C-n not worked for me too. (Firefox 65.0.2)

Following is exported config.

[{"key":"ctrl+n","action":"disable","blacklist":"false","sites":"*mail.google.com*","open":false,"activeInInputs":true,"exported":true,"sitesArray":["*mail.google.com*"]}]

**Comment by mikecrittenden** [comment]
Sadly the extension API isn't able to disable/override some specific core browser shortcuts, such as these.

**Comment by abatkin** [comment]
I think it may be worth leaving this issue open:
1) It's possible that in the future, the extension API will allow overriding these shortcuts
2) Future users will have an easier time finding that this is a "known "issue if it is still open

(after all, the issue *is* still a problem for all users, even if if it is something that you can't possibly fix at the moment)

**Comment by mikecrittenden** [comment]
@abatkin fair points but just in general I think if an issue is not actionable then it shouldn't be open, because open implies "this can be worked on". Also, there are probably 50+ closed issues in this queue that are all requests for things that we can't do with the limitations of the extension API and if we kept them all open on the off chance that they'd be supported in the future, things would get hairy.

**Comment by zw963** [comment]
I finally resolve this issue by recompile firefox by myself ......

**Comment by AndroidDeveloperLB** [comment]
@crittermike Is this answer true for CTRL+D too (add to favorites) ?
