### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by bysslord** [mikecrittenden/shortkeys#235]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Google Chrome 72.0.3626.71 beta
* Operating System and version: MacOS 10.14.2

## Current Behavior

When enable the extension, I get an error `Unchecked runtime.lastError: The message port closed before a response was received.` in console for all page.

## Steps to Reproduce (for bugs)

1. enable the extension
2. open the chrome's console
3. refresh the page

**Comment by matthewjmink** [comment]
I disabled the extension because of this. Problem existed on all pages.

**Comment by 4ice** [comment]
Is there some progress on this issue? Here is a thread regarding the issue: https://support.google.com/chrome/thread/2047906?hl=en

**Comment by ArfyFR** [comment]
Up ! Some news on this disturbing "error" ?

**Comment by zaneclaes** [comment]
I also experienced this problem and narrowed it down to this extension, forcing me to disable it. As @4ice noted, this is due to a Chrome update early this year. Many extensions were affected, as you can see in other issues complaining about the problem: https://github.com/ritwickdey/vscode-live-server/issues/270

**Comment by ArielFrischer** [comment]
> I disabled the extension because of this. Problem existed on all pages.

Same

**Comment by machineghost** [comment]
Everyone please leave reviews here: https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck?hl=en

Otherwise tons of new users will waste tons of time, as we did, just trying to track down the source of the error (which at this point looks likely never to be fixed).

**Comment by mikecrittenden** [comment]
HI all, I pushed up v3 which is a bit of an overhaul/updating of the extension code after a long hiatus. Feel free to see if that fixes the issue for you: https://github.com/mikecrittenden/shortkeys/releases/tag/v3.0.0

It'll hit the webstore next week after some more testing.

**Comment by machineghost** [comment]
Squeaky wheel, something something ... ;)

Thank you sir.

**Comment by mikecrittenden** [comment]
3.0.1 is up on the webstore now for Chrome users. Closing this issue as fixed but if someone still spots the problem, please comment back.

For Firefox users, I don't maintain that addon but note that the https://github.com/mikecrittenden/shortkeys/releases page has a package you can try.
