### ISSUE TITLE
Shortcuts not being stored

### ISSUE THREAD

**Issue by StupidMontyPythonGit** [mikecrittenden/shortkeys#239]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 65.0.2 (32-bit) 
* Operating System and version: Windows 7 

## Expected Behavior
Shortcuts should be stored

## Current Behavior
I set up shortcuts but they don't seem to be stored

## Steps to Reproduce (for bugs)
1. Tools > Addons > Shortcut Keys > Options. 
2. Specify a simple key press line ctrl+b, Do Nothing,  "ctrl B disable", check " Active while in form fields", and specify all websites, or only on (a) specific web site. 
3. Click Add
4. Exit browser
5. When I restart the browser there's no change in behavior. If I go back into the Options (step 1) I don't see the short-cut key(s) I set up listed. Shouldn't they be shown in some way in the options?

**Comment by gradha** [comment]
I just entered to comment this: I installed the extension on Firefox 66.0.2 and found the same behaviour, pressing add and not persisting my options. Turns out the Firefox windows shows the content of the extension *with scroll*, and thus you don't *see* the save button, which you have to save. Here are some screenshots on a fully maximized window (note the first screenshot doesn't show the save button):

![Captura de pantalla 2019-03-31 a las 21 31 00](https://user-images.githubusercontent.com/101927/55293990-f2177b80-53fc-11e9-8084-4fb24d7b207b.jpg)

![Captura de pantalla 2019-03-31 a las 21 31 02](https://user-images.githubusercontent.com/101927/55293995-f6439900-53fc-11e9-94b3-9a541780dfde.jpg)

**Comment by StupidMontyPythonGit** [comment]
Ahhhh!  Thanks a bunch. _Horizontal Scroll_ never occurred to me. That cured it. 

I'd feature-suggest that the Save button should be right next to the Add button instead of hidden from view... but"official" support doesn't seem to be reading these threads anyway (or I would have gotten a reply to what apparently was a very simple scenario much quicker.  No complaints, I didn't pay for support, just sayin'. :-)

Thanks again,

**Comment by MountainX** [comment]
Yes, very helpful issue / answer.

**Comment by mikecrittenden** [comment]
I don't maintain the FF addon but I believe the latest release on https://github.com/mikecrittenden/shortkeys/releases should fix this.
