### ISSUE TITLE
alt+w not working in about:addons -or- about:preferences -or- about:config

### ISSUE THREAD

**Issue by JohnDohe** [mikecrittenden/shortkeys#241]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 66.0.2
* Operating System and version: Windows 7 Ultimate (64-bit)

## Expected Behavior
pressing alt+w while in about:addons -or- about:preferences -or- about:config should open a new tab.

## Current Behavior
pressing alt+w while in about:addons -or- about:preferences -or- about:config causes nothing to happen at all.

## Steps to Reproduce (for bugs)

1. Create a shortcut using the key combination of alt+w and save it.
2. Quit the browser and re-open it.
3. Go to a tab with a URL of about:addons -or- about:preferences -or- about:config 
4. Press alt+w while in any of these Firefox tabs and nothing happens

Code:
[{"key":"alt+w","action":"newtab","blacklist":"false","sites":"*mail.google.com*","open":true,"exported":true,"sitesArray":["*mail.google.com*"],"activeInInputs":true}]

***alt+w works from any other tab: a new tab opens.  But I would like alt+w to work in the Firefox about:addons -or- about:preferences -or- about:config tabs too.

**Comment by mikecrittenden** [comment]
If you want keyboard shortcuts to also register/work on system pages such as about:config etc., you'll need to add them from the Keyboard Shortcuts section rather than in the Shortkeys config. See https://winaero.com/blog/assign-keyboard-shortcuts-extensions-firefox/

Also see: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#do-i-use-chromes-keyboard-shortcuts-settings-or-the-shortkeys-options-page
