### ISSUE TITLE
Trying to assign alt+c shortcut to about:config does not work

### ISSUE THREAD

**Issue by gh658804** [mikecrittenden/shortkeys#264]
What the title says.

## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 69
* Operating System and version: Win7x64

## Expected Behavior
Should open a new tab and open about:config in it.

## Current Behavior
Does nothing.

## Steps to Reproduce (for bugs)

1. Go to Options
2. Add alt+c as shortcut (also tried alt+w and alt+x but no luck)
3. Behavior -> jump to tab or url
4. about:config in both "URL to match" and "URL to open"

also tried checking "Active while in form fields" but nothing changed.

**Comment by mikecrittenden** [comment]
Is this Firefox or Chrome?

**Comment by gh658804** [comment]
Firefox

**Comment by mikecrittenden** [comment]
Interesting. I'm not a Firefox user but it seems like this should work. What if you add a bookmark for about:config and add a shortcut to trigger that bookmark instead?

**Comment by gh658804** [comment]
Well, another bookmark works fine. about:config does not!

**Comment by mikecrittenden** [comment]
Sounds like a plain old bug then. I'll take a look.

**Comment by mikecrittenden** [comment]
Ok, looks like this is because about:config is an invalid match pattern for the query that tries to see if a tab already exists with that URL. The best solution seems to be to just leave that field empty, and instead ONLY put it into the `URL to open if no matching tab found` field. Screenshot:

![image](https://user-images.githubusercontent.com/32261/71601125-1a650f80-2b20-11ea-8afb-ad9b61c2c917.png)

See if that works for you. Since this is such an edge case, I am going to hold off on making any code changes to try to accommodate this use case, but feel free to comment back if you think there is a code change that needs to happen here.
