### ISSUE TITLE
Search google command is broken

### ISSUE THREAD

**Issue by wolfpack92** [mikecrittenden/shortkeys#291]
I have one keyboard shortcut on this extension
and its "search google for selected text"
and its alt+s or ctrl+s

it used to work, and its not working anymore.
also i keep having to check if i wrote alt or ctrl wrong and if the spacing is the problem
so is there a way to make the alt , shift, ctrl a one button with a tic box and a box for the letter alone without having to write it down

![Capture](https://user-images.githubusercontent.com/59382298/71610056-6a7eb900-2b96-11ea-934b-42562c107ea9.JPG)

**Comment by e-rakavest** [comment]
1. Option (LOCATION: Search Google for selected text) also don't work for me.

**Comment by mikecrittenden** [comment]
Oh, looks like version 3.0.3 is still "Pending review" in the webstore for some reason, even though I submitted it days ago.

![image](https://user-images.githubusercontent.com/32261/71625449-e2a8a700-2bb5-11ea-8051-d9c87551cf70.png)

The fix for this issue is in that version. I'm not sure why it's taking so long for them to approve it, probably the holidays, but this will be fixed whenever that version is finally approved.
