### ISSUE TITLE
trigger another shortcut doesn't work

### ISSUE THREAD

**Issue by GianniGi** [mikecrittenden/shortkeys#295]
In ubuntu linux, I've tried to assign ctrl-j to the ctrl-shift-y shortcut, which shoud open the download windows, but this doesn't work... can you help? thanks

**Comment by mikecrittenden** [comment]
Yeah, the "trigger another shortcut" thing is meant to trigger another Shortkeys shortcut, rather than a built in browser one. Due to extension API limitations, the latter isn't possible. Sorry, I'm working on trying to make that less misleading.

Are you in Chrome or Firefox? If in Chrome, the following should work for opening the downloads window: 

![image](https://user-images.githubusercontent.com/32261/72007469-bd541280-321f-11ea-99f4-9e86466a8800.png)

If in Firefox, I don't believe it's possible at the moment since FF implements the Downloads popup as a window modal rather than a webpage. 

Closing this but feel free to comment back with further questions. And PRs would happily be accepted for a "Open Downloads window" action that works in Firefox and Chrome.

**Comment by GianniGi** [comment]
ah! thanks for finding the problem. I'm on firefox, so there's no solution... yet. Do you want me to open a public request here on github to see if there's interest in that?

**Comment by mikecrittenden** [comment]
Ah sorry, PR = "pull request", meaning if anyone wants to submit the code for this feature then that'd be great. 

And actually, I lied, it looks like you can enter `about:downloads` as the URL to open in Firefox and that should work. Give that a shot.

**Comment by GianniGi** [comment]
It doesn't work... probably the shortcuts are blocked by another extension.... I'll try to find why it doesn't work.
