### ISSUE TITLE
Multiple shortcuts for a single option

### ISSUE THREAD

**Issue by R-Bower** [mikecrittenden/shortkeys#296]
I switch some modifier keys to CTRL or ALT depending on whether I'm docked (external keyboard) or mobile (laptop keyboard).  Is there any way to add more than one shortcut for the same option?

**Comment by mikecrittenden** [comment]
So you want to have 2 different keyboard shortcuts that point to the same action? Sure, that should work fine. Here's an example of having both `ctrl+shift+j` and `alt+shift+j` point to scroll down:

![image](https://user-images.githubusercontent.com/32261/72196594-54b79200-33e7-11ea-9c43-e2f2e3491198.png)

**Comment by R-Bower** [comment]
Sure, that's always been possible from the App menu.  But what about from Chrome's built-in shortcuts for the app's extensions?  
![image](https://user-images.githubusercontent.com/11933208/72211108-6f871680-347a-11ea-8f03-a84bb60673bf.png)

Commands like **Previous tab** have limitations, as you've outlined here:
![image](https://user-images.githubusercontent.com/11933208/72211136-e1f7f680-347a-11ea-9b0e-0c2d2e1ec6de.png)

Seems like this would be a better question for the Chrome dev team.  Regardless, have you found a way to add multiple bindings to the built-in Chrome shortcuts?

**Comment by mikecrittenden** [comment]
Ah yes, now I understand. The only way for Shortkeys to support that would be for Shortkeys to have duplicates on that page, so like for example we could have 3 of each one instead of just 1 of each one, so that you could add 3 shortcuts per action. I'd prefer to avoid that because that page is already a giant list as it is and I'd rather not double or triple the size of it. And there's no way in the API for us to categorize things or make them searchable on that page (hence me prefixing each one with "TABS:" for example).
