### ISSUE TITLE
Printing?

### ISSUE THREAD

**Issue by anythingwithawire** [mikecrittenden/shortkeys#298]
I would like to be able to print all tabs with a shortcut, seems I would need to write some javascript and then I might as well not buy the shortkeys?

Am I missing something, I only invested 5 minutes in trying to work this out?

**Comment by mikecrittenden** [comment]
You mean print as in, send to your physical printer to print every single one of your tabs on paper? What if you have 100 open tabs?

**Comment by anythingwithawire** [comment]
you would look foolish

**Comment by mikecrittenden** [comment]
I'm actually not sure how this would work, since calling .print() opens up the print dialog rather than immediately printing, so in the case of multiple tabs it would open a ton of print dialogs I guess?

In any case, this seems like a very narrow use case and I try to shy away from adding functionality to Shortkeys that only 1 or 2 people might use, so I'm going to close this ticket unless others speak up that they'd like this.
