### ISSUE TITLE
Jump keys not working for this new user - what am I doing wrong?

### ISSUE THREAD

**Issue by paulgsilva** [mikecrittenden/shortkeys#345]
Happy day. I'm a new user, read the instructions, saw the warnings about being sure to refresh, but somehow I am goofing it up and can't get this to work on my mac or chromebook. I also found errors in the mac version (frowning faces when you click the support or shortcut key help links). I made a video (linked below) showing what I am doing so you can see clearly. I am almost certainly doing something simple and foolishly wrong. My thanks in advance for the help. 

https://drive.google.com/file/d/1MY6HXvx92jPcmEC9VpJ5_uwi-uP-Alg_/view?usp=sharing

**Comment by mikecrittenden** [comment]
Hey there! Looks like your problem is that when adding shortcuts via the Shortkeys config, those shortcuts only work when you have regular pages (i.e., NOT the extension page, or the Chrome web store) opened. Chrome's extension API doesn't allow extensions to add JS to the extensions pages or the web store pages, so it's impossible for Shortkeys to support those specific pages. See more info here: https://gitlab.com/phase2tech/webster-bank/webster-bank/-/merge_requests/1696 (first bullet point in particular). Does that help?
