### ISSUE TITLE
"No longer available" on Chrome Web Store

### ISSUE THREAD

**Issue by Wyatts** [mikecrittenden/shortkeys#396]
Bringing up a new computer and was surprised to find that I can't install this through normal means.  What even happened? (i.e. what boneheaded thing did Google do this time?)

**Comment by mikecrittenden** [comment]
You don't see it here? https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck/reviews?hl=en-US&gl=US

**Comment by Wyatts** [comment]
Yeah, I see the page, but instead of a button to install it, there's a greyed out button-shaped box that says "No longer available".

**Comment by knw257** [comment]
Here's what I see when I visit that page @mikecrittenden 

![image](https://user-images.githubusercontent.com/11547080/107153852-b2494580-693d-11eb-9007-c794da9e89a1.png)

**Comment by mikecrittenden** [comment]
Well...what the heck. I haven't gotten any notifications from the web store. It still says it's published in the developer dashboard. I'll keep digging.

What Chrome version are you on?

**Comment by Wyatts** [comment]
I'm seeing it on Chrome 87 and 88.   Also, for the record, the existing installation _hasn't stopped working_ for me.  Just can't get a new one.

**Comment by joshandersn** [comment]
I just found this too I'm trying to install it from the source code

**Comment by aloofbit** [comment]
Hi, I am also seeing `No Longer Available`
Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by mikecrittenden** [comment]
I *think* I figured out the problem and submitted an update to fix it. We'll see if it gets approved in the next day or two.

**Comment by aloofbit** [comment]
Ty @mikecrittenden !! I was able to install the plugin now through webstore. I appreciate the work on this plugin it is very helpful.

**Comment by mikecrittenden** [comment]
Gotcha. The problem was that Google [deprecated monetized Chrome extensions](https://developer.chrome.com/docs/webstore/cws-payments-deprecation/). I thought that was happening in March but it turns out it was February. So I had to change it back to a free extension. :(

**Comment by ntap-leeray** [comment]
@mikecrittenden I have it just installed (Feb 28, Singapore time) but it's on a Cloudready installation. I defined only 1 shortcut just to test it out: "q" to "Close Tab". It does not work. On the list of extension (the icon that looks like a puzzle piece at the top right-hand corner of browser), Shortkeys is greyed out. Clicking on the 3 dots, I can choose "Manage Extension" hence I can add the shortcut above.

Is there something I have missed? Is installation on Cloudready not supported? Thanks.

**Comment by mikecrittenden** [comment]
I'm not sure what Cloudready is so I guess it's not officially supported, but it seems like if you're able to reach the settings page then the extension should work. Were you sure to refresh any tabs you were testing on after adding that shortcut?

**Comment by ntap-leeray** [comment]
@mikecrittenden Cloudready is a Chromium based OS that behaves almost like ChromeOS that runs on Chromebook. It's made by a company called Neverware which was recently acquired by Google. Neverware make Edu and Enterprise focus tools (to manage the computers running Cloudready). There is also a home version which many of us install on old laptops that struggle to run Windows or MacOS.

Anyway, I think Shortkeys IS working. It just happens that on some special pages, it does not. The three pages which do not work (that I have kept trying and incorrectly concluded that it didn't work) are: New Tab page, even when cursor is not on URL input field, webstore page (chrome.google.com/webstore...), and the Extension Option page (where you define the shortcuts). There maybe are others.

But the original purpose for me to install this extension is fulfilled: when I am on Google News, clicking on news items opens a new tab. After reading, I want a quick way to close that tab instead of clunkily clicking Ctrl-W. It works. Thanks for the work!
