### ISSUE TITLE
New "Manage your downloads" permission?

### ISSUE THREAD

**Issue by eichin** [mikecrittenden/shortkeys#400]
Running 4.0.1 from chrome store chrome://extensions/?id=logpjaacgmcbpdkdchjiaagddngobkck linux chrome 88.0.4324.146, and (without restarting or reinstalling anything - main process running since 6 Feb 2021) my bindings stopped working and I got an orange `Error` box on the upper right menu.  Top line says "Shortkeys (Custom Keyboard Shortcuts) is disabled"; clicking on that gets a box with the same header and "To re-enable it, accept the new permissions: Manage your downloads [remove] [accept permissions]".

I don't see anything in release notes or even recent merges, and https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#why-are-all-these-permissions-required is great but hasn't changed in over a year... maybe google changed the scope need for the "browse data/clear downloads" case listed there?

**Comment by eichin** [comment]
(Restarted chrome, still says 88.0.4324.146 though. Not objecting to the permission itself, but I'm a little paranoid about unexplained permissions changes;   chrome webstore does say 4.0.1 went up yesterday, so it must have auto-updated or something.)

**Comment by mikecrittenden** [comment]
Hey hey - is there a chance you installed Shortkeys over a year ago? If so, probably what happened is that you were stuck at an old version for the last year since I changed it to be monetized and it only upgrades you if you pay. And then yesterday I switched it back to be free so you jumped forward a bunch of versions all at once. 

Anyways, about that permission specfically, it's because we added the "show latest download" action which requires it. Here's the specific commit: https://github.com/mikecrittenden/shortkeys/commit/f74e33dff64df224a2eea22d87fa0714d3ae3ca5
