### ISSUE TITLE
Add reason for debugger permission requirement to wiki page

### ISSUE THREAD

**Issue by ryancu7** [mikecrittenden/shortkeys#447]
Chrome warned me today that shortkeys now requires permission to "Access the page debugger backend". I went to the wiki page https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#Why_are_all_these_permissions_required to find out why but this new permission is not listed. Commit ff32f7a1542a071251256fb76acb0881a998cb79 implies it is required for taking a screenshot of the viewport. Can this be added to the wiki page, please?

**Comment by mikecrittenden** [comment]
Thank you, I forgot to update that page! Done, and it was also missing info about the "Manage your downloads" permission so I added that too.

**Comment by random-un** [comment]
Thanks for the quick reply here! Some quick comments:

- Chrome is also asking me to "accept the new permissions" for "Read and change all your data on the websites you visit" (see screenshot below). This is confusing as I believe this was always a required permission. Are you able to elaborate on the change that caused Chrome to request the permission again?
- The FAQ for the "Access the page debugger backend" permission reads: "This is required for taking screenshots of the page on demand" -- are you able to elaborate on what this means?


I love Shortkeys and am sure the extension continues to be private and secure, but am curious about the new permissions and thought I'd ask for myself and anyone else interested in this topic. Thanks!


![image](https://user-images.githubusercontent.com/35006176/128646552-b6aa602c-016f-4797-881a-d19090d9ccd9.png)

**Comment by mikecrittenden** [comment]
Hi there! Good questions. 

Re: the "Read and change all your data on the websites you visit" - I honestly have no idea why Chrome would want you to re-accept that. It has always been there - it's a required permission in order to inject content scripts to interact with the page itself. Maybe it's just such a powerful/scary permission that Google sticks it back in there every time there's any permission change? But yes, nothing has changed on the Shortkeys side related to that.

Re: screenshots, there are new actions to capture screenshots of either the viewport or the full page. This came from PR #403 if you want to review the code. Capturing screenshots is considered a feature of the Chrome debugger, therefore we need debugger permission to offer that.
