### ISSUE TITLE
Add "Run JS in background script" for running custom JS that has access to browser APIs

### ISSUE THREAD

**Issue by mikecrittenden** [mikecrittenden/shortkeys#76]
This would effectively give people to the power to do anything they want, theoretically. Note however that we can't use `eval()` due to Chrome's CSP, and we'd be limited by the permissions that the extension already requests (I think).

**Comment by mikecrittenden** [comment]
The `eval()` issues seem to make this one a non-starter, as far as I can tell.

**Comment by mikecrittenden** [comment]
Sadly I can't seem to find a good way to accomplish this. It would need to use `eval()` to run the JS that gets entered (as far as I know), and the browsers don't allow that without either 1) sandboxing the page (which denies access to extension APIs) or 2) relaxing the content security policy, which browsers (Chrome at least) strongly recommends that you don't do (see https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval). I'm afraid I have to re-close it based on that.

**Comment by mikecrittenden** [comment]
Reopening this because @Lej77 has created a PR to address this: https://github.com/mikecrittenden/shortkeys/pull/149

**Comment by orthoceros** [comment]
Thanks, this is good news. I am really looking forward for this! :) The FoxyGestures addon already provides an executeInBackground function for user scripts. In this way, we can automate the browser or other addons like TreeStyleTabs (e.g., [my script for collapsing all nodes in the tab tree](https://github.com/marklieberman/foxygestures/wiki/List-of-Common-User-Scripts#collapse-all-nodes-in-the-tabs-tree-of-the-tree-style-tabs-addon)). Ideally, you could replicate the function signature from FoxyGestures/executeInBackground. Then we could (re)use identical user scripts for both gestures and keyboard shortcuts. Would that be compatible with your design?

**Comment by Lej77** [comment]
@orthoceros I don't know if that would be possible. There are some fundamental differences in my suggested implementation and the one used by the FoxyGestures addon. My implementation is more restricted since it can't use `eval` in the background script. FoxyGestures has `unsafe-eval` in its `content_security_policy` in the [manifest.json](https://github.com/marklieberman/foxygestures/blob/master/src/manifest.json#L33) file to allow this, but that is not recommended as stated by @mikecrittenden previously. 

So FoxyGestures executes all of the code in the backround script which means that it can change variables and create eventListeners that implement behavior that remains until the extension is restarted. My implementation's user code is bound to a tab's page which means that if the page is reloaded then the user script is stopped. (Not necessarily the tab that the script was started in since the user's script can be executes in another tab with the [tabs.executeScript()](https://developer.mozilla.org/Add-ons/WebExtensions/API/tabs/executeScript) function.) Anyways this means that directly accessing the WebExtensions variable is a bit difficult. 

I can think of two possible ways to emulate FoxyGestures behavior. The first is to simply convert the user's function to a string and then parse it so that all `browser` and `chrome` references are changed to the `call('browser.` / `call('chrome.` signatures. Another would be to create an object with the same property names as the extension variable but using the `call` / `get` functions to emulate the properties behavior. The second method would probably be preferable. I have updated my pull request with support for my second solution.

**Comment by orthoceros** [comment]
Thanks for the info. Binding user scripts to the life scope of the starting tab sounds reasonable/okay for me. At least at the moment, I cannot imagine any useful user script that first has to close its hosting tab and then still perform some actions or react on some subscribed events.
Emulating browser.* properties via call/get also sounds convenient. I'm just not sure if this would play nicely with the await syntax inside async functions? For example, when accessing TreeStyleTab APIs like the `treeInfo4activeWindow = await browser.runtime.sendMessage('treestyletab...` line in the example script linked above?

**Comment by Lej77** [comment]
@orthoceros I implemented a `executeInBackground` function in my pull request that creates a dummy object for each extension object (such as `chrome` and `browser`) so when the `browser` variable is used in the passed function it is actually referencing the dummy object. This seems to work fine for the [Collapse all nodes in the tabs tree of the Tree Style Tabs addon](https://github.com/marklieberman/foxygestures/wiki/List-of-Common-User-Scripts#collapse-all-nodes-in-the-tabs-tree-of-the-tree-style-tabs-addon) and the [Maximize/Restore Window](https://github.com/marklieberman/foxygestures/wiki/List-of-Common-User-Scripts#maximizerestore-window) FoxyGestures scripts. The `await` keyword is not a problem since the dummy object always returns with a promise. It might be a problem if the script tries to access an extension variable that isn't normally a promise such as [browser.runtime.id](https://developer.mozilla.org/Add-ons/WebExtensions/API/runtime/id).
