### ISSUE TITLE
Add "Trigger another shortcut" action to have multiple ways to trigger the same shortcut

### ISSUE THREAD

**Issue by ambrt** [mikecrittenden/shortkeys#93]
I have "ctrl+ernter' shortcut, how can i trigger it from 'alt+enter' without copying one to other?

**Comment by mikecrittenden** [comment]
Currently there's no way to do that, but we could add a "Trigger other shortcut" action I suppose. Can I ask what the use case is? Like, why do you want 2 different ways to trigger the same shortcut?

**Comment by sterbalr** [comment]
Typically I want to do this in other applications where I use the keyboard differently for different situations. The most common is in SQL Server Management studio. If I'm holding the mouse to select text I might use the F5 key to execute, otherwise I use the CTRL+E shortcut.

**Comment by ambrt** [comment]
The  original case is that i have multiple jQuery queries for a websites (submit buttons on different pages) in one big function.

The need for different shortcuts for same functionality is that i'm used to different shortcuts used in other enviroments (like linux `nano` has ctrl+o to save, and windows `notepad` has ctrl+s to save) so sometimes i habitually use one of them.

When i adding  new part of a function or adding a new shortcut with same func, i'd need to copy whole  updated function to different shortcuts every time i change something.

@mikecrittenden  If i understand well, You suggest to add Trigger another shortcut from "Behavior" menu. I'd suggest to also allow triggering it from within the Js code to be more flexible and cover use case like @sterbalr  well described.

**Comment by mikecrittenden** [comment]
Good point @ambrt. That seems possible. I was hoping you could just call `Mousetrap.trigger('ctrl+a')` directly like the docs suggest https://craig.is/killing/mice#api.trigger but since Mousetrap lives as a content script, and your custom JS lives as an actual script tag that's inserted into the page, that doesn't work unfortunately. But I'm sure I could find a workaround for that.

**Comment by ambrt** [comment]
> But I'm sure I could find a workaround for that.

That would be great. Keep us in the loop about it!

**Comment by mikecrittenden** [comment]
I pushed https://github.com/mikecrittenden/shortkeys/commit/10ae3f5b72a2aae61b82a6097c47ee1eec59cc4f which does the following:

![2017-12-08 at 9 26 pm](https://user-images.githubusercontent.com/32261/33791724-791d3646-dc5e-11e7-82cf-09e5b80f9b83.png)

What do you all think of that? Obviously it's a little awkward that the text field is super wide, but otherwise, is that kind of what you had in mind?

**Comment by ambrt** [comment]
I wouldn't mind the width issue. Will you push it to chrome store? It looks good to me.

**Comment by mikecrittenden** [comment]
Pushed to v2.2.5 and uploaded to webstore. Thanks!
